### ISSUE TITLE
Motor holder with Switchmount missing

### ISSUE THREAD

**Issue by zenzmatz** [AndBu/YAIFM#1]
Hi,

In the Mockup of all 3D-Printed parts, and in the "Printing parts section" you are mention YAIFM_motor_holder.stl with an mount for the YAIFM_switch_holder.stl, but it looks like, you didn't uploaded it yet.

Could you upload this file?

**Comment by shawru** [comment]
Also noticed this, did you get any update?

**Comment by AndBu** [comment]
Sorry, slipped my attention. Will upload on the weekend :)

**Comment by AndBu** [comment]
Uploaded.
