### ISSUE TITLE
Provide step-files for 3D-printed parts

### ISSUE THREAD

**Issue by benbender** [AndBu/YAIFM#2]
Hey,

first and foremost: Very nice project! Thank you for putting in the work and sharing the results!

I'm in the process of replicating the project and started with 3d-printing parts and sourcing materials.
To make it perfectly fit for my circumstances I would like to do some modifications like having a closed box für the electronics.
To do this, it would be quite helpful to have the step-files for the 3d-prints so I don't have to measure myself and reinvent the wheel.

Could you provide those?

**Comment by AndBu** [comment]
Thanks for the comment. I have now uploaded the step files as well.

**Comment by benbender** [comment]
Thank you very much! <3

**Comment by AndBu** [comment]
I could also upload the Fusion design files if that helps but they might need some cleaning up to be really useful.
